name: an_muk_so
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #firebase
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2
  firebase_dynamic_links: ^0.5.3
  firebase_storage: ^5.2.0
  #firebase_ml_vision: ^0.11.0

  #login
  google_sign_in: ^4.5.1
  mask_text_input_formatter: ^1.0.7
  shared_preferences: ^0.5.12+4
  logger: ^0.9.4  #optional
  flutter_facebook_auth: ^2.0.1

  #state management
  provider: ^4.3.2+3

  #camera
  camera: ^0.7.0+2
  path_provider: ^1.6.27
  path: ^1.7.0
  xfile: ^1.1.0

  #functions
  flappy_search_bar: ^1.7.2
  smooth_star_rating: ^1.1.1
  flutter_rating_bar: ^3.2.0+1
  rating_bar: ^0.2.0
  fl_chart: ^0.12.2
  flutter_datetime_picker:
    git:
      url: https://github.com/espresso3389/flutter_datetime_picker

  #and so on
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9
  connectivity: ^2.0.2
  google_fonts: ^1.1.1
  pedantic: ^1.9.2
  flutter_spinkit: ^4.1.2+1
  fluttertoast: ^7.1.6
  dynamic_text_highlighting: ^2.2.0
  carousel_slider: ^3.0.0

  #case recognition
  tflite: ^1.0.4
  image_picker: ^0.6.2+3




dev_dependencies:
  flutter_test:
    sdk: flutter

#스플레쉬 화면을 위한 패키지
flutter_native_splash:
  image: assets/logo/splash_3x.png
  color: "#FFFFFF"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  #assets:
    #아래꺼는 이약모약에서 가져온 거라서 수정 필요함!
    #- assets/camera/
    #- assets/icons/
    #- assets/images/
    #- assets/case_model/model_unquant.tflite
    #- assets/case_model/labels.txt
    #여기까지 이약모약 필요한 파일 구성해서 가져오기

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


#이약모약에서 가져온 폰트 넣어두어야 한다.
#fonts:
  #- family: NotoSansKR
    #fonts:
      #- asset: assets/fonts/NotoSansKR-Bold.otf
      #- asset: assets/fonts/NotoSansKR-Medium.otf
      #- asset: assets/fonts/NotoSansKR-Regular.otf

  #- family: NotoSansCJKKR
    #fonts:
      #- asset: assets/fonts/NotoSansCJKkr-Regular.otf
#여기까지 이약모약꺼 가져온거


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
